# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guitab.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(692, 495)
        self.testtab = QtWidgets.QTabWidget(Form)
        self.testtab.setGeometry(QtCore.QRect(0, 10, 281, 211))
        self.testtab.setObjectName("testtab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.labelontab = QtWidgets.QLabel(self.tab)
        self.labelontab.setGeometry(QtCore.QRect(100, 90, 67, 19))
        self.labelontab.setObjectName("labelontab")
        self.testtab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.testtab.addTab(self.tab_2, "")
        self.labeonwidget = QtWidgets.QLabel(Form)
        self.labeonwidget.setGeometry(QtCore.QRect(400, 220, 67, 19))
        self.labeonwidget.setObjectName("labeonwidget")

        self.retranslateUi(Form)
        self.testtab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelontab.setText(_translate("Form", "TextLabel"))
        self.testtab.setTabText(self.testtab.indexOf(self.tab), _translate("Form", "Tab 1"))
        self.testtab.setTabText(self.testtab.indexOf(self.tab_2), _translate("Form", "Tab 2"))
        self.labeonwidget.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
